spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://user-db:3306/user_db?useSSL=false&serverTimezone=UTC}
    username: ${DB_USERNAME:user_user}
    password: ${DB_PASSWORD:user_pass}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

logging:
  level:
    com.zjgsu.user: WARN
